### ISSUE TITLE
Developer tools open every time I boot fanbox.

### ISSUE THREAD

**Issue by ChildishGiant** [joereynolds/fanbox#6]
This may be todo with the errors I get when starting:
`Gtk-Message: Failed to load module "pantheon-filechooser-module"
Electron could not be found. No hard resets for you!
`
I'm on Elementary OS (Ubuntu 14.04)

**Comment by joereynolds** [comment]
Hey there, this is because it's currently on by default. For now (until I push up maybe tomorrow) you can just comment out line 35 in `main.js` :)

**Comment by ChildishGiant** [comment]
Thanks :D

**Comment by ChildishGiant** [comment]
I also agree with the comment on line 34 about adding it to the config :smile:
