### ISSUE TITLE
Node errors when trying to install fanbox

### ISSUE THREAD

**Issue by nomko** [joereynolds/fanbox#7]
Hi,

I canot install Fanbox on a Linux Mint 18 Xfce setup.
I get a lot of node errors, see here for my post on Linux Mint forum:
https://forums.linuxmint.com/viewtopic.php?f=47&t=227766&p=1205370#p1203599

What to do and how to fix this?

**Comment by joereynolds** [comment]
Hi @nomko 

I'll read through that forum post later on but for now can you tell me the specific console errors you are getting?

What version of node are you using?

Update:
Looking at it, you've got 2 potential problems (that I can spot).

1) You haven't got node installed in which case just do `sudo apt-get install nodejs`

2) Your symlink to node is broken. You need to link node to nodejs for various reasons
`sudo ln -s /usr/bin/nodejs /usr/bin/node`

Do either of those work?

Cheers

**Comment by joereynolds** [comment]
Hi @nomko 

I'm closing this since I don't think it's an issue and I haven't had a reply from you in a looooong time.

Cheers,
Joe
